# The Docker image that will be used to build your app
image: python:3.9
# Functions that should be executed before the build script is run
before_script:
  - apt-get update && apt-get install -y build-essential
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install numpy sphinx sphinx-rtd-theme scikit-learn
    qpsolvers[quadprog,scs,proxqp]>=4.3.2 proxsuite matplotlib pandas>=2.1.1
    pyarrow seaborn tabulate scipy scs tqdm>=4.66.1 torch>=2.0.1
pages:
  script:
    - source venv/bin/activate
    - cd docs
    - make html
    - mv build/html ../public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
